# -*- coding: utf-8 -*-
"""Anomaly detection using Pycaret.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GSilQNUt5-qc4SiIt7v8GluT3Ozvu0qA
"""

# importing necessary libraries

!pip install pycaret
import pandas as pd

# Mounting the google drive

from google.colab import drive
drive.mount('/content/drive/')

# Loading the data in two Pandas dataframes

data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/MRP/creditcard.csv')

from pycaret.anomaly import *

# The setup function prepares the data. It does all the preprocessing.

exp_ano = setup(data)

# creating the model

iforest = create_model('iforest')

predictions = predict_model(iforest, data = data)

predictions

predictions['Class']

# model performance evaluation by classification_report, confusion_matrix

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(predictions['Label'], predictions['Class']))

confusion_matrix(predictions['Label'], predictions['Class'])